### ISSUE TITLE
Throw in ISequencer::next(N) when N > bufferSize

### ISSUE THREAD

**Issue by andrewkcorcoran** [Abc-Arbitrage/Disruptor-cpp#10]
Otherwise it's possible to get a deadlock where the producer is waiting for >N free slots which will never become free.

e.g.

https://github.com/LMAX-Exchange/disruptor/blob/master/src/main/java/com/lmax/disruptor/SingleProducerSequencer.java#L119
vs
https://github.com/Abc-Arbitrage/Disruptor-cpp/blob/master/Disruptor/SingleProducerSequencer.h#L89

**Comment by oktal** [comment]
Hello,

Thanks for raising the issue.

This has been fixed in https://github.com/Abc-Arbitrage/Disruptor-cpp/commit/419460209212124e3d5df7904825009e62fd59d1

**Comment by andrewkcorcoran** [comment]
Hi thanks for the fix, however it looks like the fix is only for `SingleProducerSequencer`, the issue is also present in `MultiProducerSequencer`.
