### ISSUE TITLE
Undefined Behaviour: Integer overflow on Sequence increment

### ISSUE THREAD

**Issue by andrewkcorcoran** [Abc-Arbitrage/Disruptor-cpp#11]
`Disruptor/EventPoller.h:57:37: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long`

Java guarantees deterministic overflow behavior for signed integers but C++ doesn't resulting in undefined behaviour in various locations throughout the code - the above is only one example.

**Comment by oktal** [comment]
Hello,

You are right, signed integer overflow is undefined behavior in C++.

However, I'm curious about Java and the JLS, does it guarantee a 2-complement representation for signed integers, thus shifting the sign bit when overflowing ?

**Comment by andrewkcorcoran** [comment]
I'm not a jls expert so I can't see anything in the standard that
explicitly states what happens. However, everything I can find on
stackoverflow etc. states that java gaurantees to wrap around to the
minimum value.
