### ISSUE TITLE
Eliminate overhead of std::function in `EventPoller`

### ISSUE THREAD

**Issue by andrewkcorcoran** [Abc-Arbitrage/Disruptor-cpp#12]
https://github.com/Abc-Arbitrage/Disruptor-cpp/blob/master/Disruptor/EventPoller.h#L39 could be trivially refactored to take a forwarding reference as the eventHandler instead of a `std::function`. This would eliminate the potential for memory allocation when the `std::function` is constructed and the virtual call when the `eventHandler` is invoked.

**Comment by oktal** [comment]
Hello,

You are right, the `eventHandler` is not stored anywhere so we do not need a `std::function` there.

Do you want to submit a Pull Request ?

**Comment by andrewkcorcoran** [comment]
As it's such a simple change, if there's someone else who can submit the PR it would be a lot faster than waiting on me as the internal process I have to follow for external code contributions can take a while.

**Comment by slumber** [comment]
I can do this if you don't mind. @andrewkcorcoran

**Comment by andrewkcorcoran** [comment]
That's great Chris thanks.

**Comment by ybainier** [comment]
That's great, thanks! Could someone static assert the signature of the function to display a friendly compile time error?
