### ISSUE TITLE
Sequencer supported types?

### ISSUE THREAD

**Issue by keineahnung2345** [Abc-Arbitrage/Disruptor-cpp#16]
I'd like to put `vector`, `variant`, `unique_ptr`, `string`, `Eigen::VectorXf` into the queue, is it possible?

**Comment by Andreone** [comment]
Sequencer is an implementation detail not related to the type of the queue entries.
You can push anything in the queue. It's best to create a struct and use it with the types disruptor<T> and IEventHandler<T>.
