### ISSUE TITLE
Compile with GCC 4.8.2

### ISSUE THREAD

**Issue by zhanyigo** [Abc-Arbitrage/Disruptor-cpp#3]
Hi,
It not work on CentOS 7. Any plan of this?

**Comment by anokl** [comment]
Hi, 
No, sorry.  You are supposed to use GCC 5.0 or newer as stated on the project home page.

**Comment by zhanyigo** [comment]
But a lot of server app run on rhel or centos.

**Comment by anokl** [comment]
Yes you are right. But it is not about OS it's about compiler version. We use Debian family here but I don't see any reason why it should not work on Redhat/CentOS if you use the proper compiler version.

**Comment by zhanyigo** [comment]
I think I can install gcc-6. Thanks.
https://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2
