### ISSUE TITLE
What flags are required to compile?

### ISSUE THREAD

**Issue by muffinrecon** [Abc-Arbitrage/Disruptor-cpp#5]
I am trying to compile with gcc, but I am unaware of what linker flags I need to add it to my project. 

Thanks

**Comment by anokl** [comment]
Hi @muffinrecon, you should link against Disruptor library indeed and also all its dependencies. The minimal  command line could be like following:

`g++ ./test.cpp -std=c++14 -fPIC -I<disruptor_include_dir> -I<boost_include_dir> -L<disruptor_lib_dir> -L<boost_lib_dir> -lDisruptor -lboost_system -lboost_thread -lboost_chrono -lboost_date_time -lpthread`

**Comment by muffinrecon** [comment]
Thank you very much. FYI for anyone getting an error stating that the library can't be found. Try using this command:

`sudo ldconfig
`

Turned out that the package manager did not update the cache for me after using these flags
