### ISSUE TITLE
Is there anyway to bind an eventhandler/workhandler to a certain cpu core?

### ISSUE THREAD

**Issue by muffinrecon** [Abc-Arbitrage/Disruptor-cpp#6]
What i want to do is control which eventhandler gets to use which cpu core, so I can disable hyperthreading on a few cores and enable it on another.

**Comment by MendelMonteiro** [comment]
Have a look at this entry on the LMAX blog : 
https://www.lmax.com/blog/staff-blogs/2015/09/26/reducing-system-jitter/

**Comment by muffinrecon** [comment]
Ok Thanks. 

I took a look at Lifecycle nterface and understand that I need to setaffinity when the onStart event is called
