### ISSUE TITLE
Is it lock-free?

### ISSUE THREAD

**Issue by upider** [Abc-Arbitrage/Disruptor-cpp#8]
How it can be lock-free when you use condition_variable and unique_lock?

**Comment by ybainier** [comment]
Hi, you can configure your wait strategy to choose a lock-free one. `BusySpinWaitStrategy` for instance is a good candidate. Whatever strategy you end up choosing, make sure to benchmark your solution beforehand, there is no one size fits all regarding this component.

Read more about wait strategies over here : https://github.com/LMAX-Exchange/disruptor/wiki/Getting-Started#alternative-wait-strategies
